import { PrismaClient, Status } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // === USUÁRIOS REAIS (100) ===
  const usersData = [
    {
      name: "Ana Silva",
      email: "ana.silva@senaisp.org.br",
      phone: "11998765401",
      password: "senha123",
    },
    {
      name: "Bruno Souza",
      email: "bruno.souza@senaisp.org.br",
      phone: "11998765402",
      password: "senha123",
    },
    {
      name: "Carlos Oliveira",
      email: "carlos.oliveira@senaisp.org.br",
      phone: "11998765403",
      password: "senha123",
    },
    {
      name: "Daniela Santos",
      email: "daniela.santos@senaisp.org.br",
      phone: "11998765404",
      password: "senha123",
    },
    {
      name: "Eduardo Lima",
      email: "eduardo.lima@senaisp.org.br",
      phone: "11998765405",
      password: "senha123",
    },
    {
      name: "Fernanda Gomes",
      email: "fernanda.gomes@senaisp.org.br",
      phone: "11998765406",
      password: "senha123",
    },
    {
      name: "Gabriel Rodrigues",
      email: "gabriel.rodrigues@senaisp.org.br",
      phone: "11998765407",
      password: "senha123",
    },
    {
      name: "Helena Almeida",
      email: "helena.almeida@senaisp.org.br",
      phone: "11998765408",
      password: "senha123",
    },
    {
      name: "Igor Ferreira",
      email: "igor.ferreira@senaisp.org.br",
      phone: "11998765409",
      password: "senha123",
    },
    {
      name: "Juliana Pereira",
      email: "juliana.pereira@senaisp.org.br",
      phone: "11998765410",
      password: "senha123",
    },
    // Continuação até 100 usuários
    {
      name: "Kauã Martins",
      email: "kaua.martins@senaisp.org.br",
      phone: "11998765411",
      password: "senha123",
    },
    {
      name: "Laura Costa",
      email: "laura.costa@senaisp.org.br",
      phone: "11998765412",
      password: "senha123",
    },
    {
      name: "Lucas Ribeiro",
      email: "lucas.ribeiro@senaisp.org.br",
      phone: "11998765413",
      password: "senha123",
    },
    {
      name: "Manuela Carvalho",
      email: "manuela.carvalho@senaisp.org.br",
      phone: "11998765414",
      password: "senha123",
    },
    {
      name: "Nicolas Barbosa",
      email: "nicolas.barbosa@senaisp.org.br",
      phone: "11998765415",
      password: "senha123",
    },
    {
      name: "Olivia Alves",
      email: "olivia.alves@senaisp.org.br",
      phone: "11998765416",
      password: "senha123",
    },
    {
      name: "Pedro Dias",
      email: "pedro.dias@senaisp.org.br",
      phone: "11998765417",
      password: "senha123",
    },
    {
      name: "Rafaela Barros",
      email: "rafaela.barros@senaisp.org.br",
      phone: "11998765418",
      password: "senha123",
    },
    {
      name: "Samuel Mendes",
      email: "samuel.mendes@senaisp.org.br",
      phone: "11998765419",
      password: "senha123",
    },
    {
      name: "Sofia Moreira",
      email: "sofia.moreira@senaisp.org.br",
      phone: "11998765420",
      password: "senha123",
    },
    {
      name: "Thiago Nogueira",
      email: "thiago.nogueira@senaisp.org.br",
      phone: "11998765421",
      password: "senha123",
    },
    {
      name: "Valentina Cunha",
      email: "valentina.cunha@senaisp.org.br",
      phone: "11998765422",
      password: "senha123",
    },
    {
      name: "Vinicius Pires",
      email: "vinicius.pires@senaisp.org.br",
      phone: "11998765423",
      password: "senha123",
    },
    {
      name: "Yasmin Azevedo",
      email: "yasmin.azevedo@senaisp.org.br",
      phone: "11998765424",
      password: "senha123",
    },
    {
      name: "Arthur Castro",
      email: "arthur.castro@senaisp.org.br",
      phone: "11998765425",
      password: "senha123",
    },
    {
      name: "Beatriz Pinto",
      email: "beatriz.pinto@senaisp.org.br",
      phone: "11998765426",
      password: "senha123",
    },
    {
      name: "Davi Rezende",
      email: "davi.rezende@senaisp.org.br",
      phone: "11998765427",
      password: "senha123",
    },
    {
      name: "Esther Viana",
      email: "esther.viana@senaisp.org.br",
      phone: "11998765428",
      password: "senha123",
    },
    {
      name: "Felipe Melo",
      email: "felipe.melo@senaisp.org.br",
      phone: "11998765429",
      password: "senha123",
    },
    {
      name: "Giovanna Farias",
      email: "giovanna.farias@senaisp.org.br",
      phone: "11998765430",
      password: "senha123",
    },
    {
      name: "Heitor Cardoso",
      email: "heitor.cardoso@senaisp.org.br",
      phone: "11998765431",
      password: "senha123",
    },
    {
      name: "Isabella Correia",
      email: "isabella.correia@senaisp.org.br",
      phone: "11998765432",
      password: "senha123",
    },
    {
      name: "João Ramos",
      email: "joao.ramos@senaisp.org.br",
      phone: "11998765433",
      password: "senha123",
    },
    {
      name: "Lara Lopes",
      email: "lara.lopes@senaisp.org.br",
      phone: "11998765434",
      password: "senha123",
    },
    {
      name: "Leonardo Vieira",
      email: "leonardo.vieira@senaisp.org.br",
      phone: "11998765435",
      password: "senha123",
    },
    {
      name: "Maria Clara Sales",
      email: "maria.sales@senaisp.org.br",
      phone: "11998765436",
      password: "senha123",
    },
    {
      name: "Miguel Teixeira",
      email: "miguel.teixeira@senaisp.org.br",
      phone: "11998765437",
      password: "senha123",
    },
    {
      name: "Nicole Fernandes",
      email: "nicole.fernandes@senaisp.org.br",
      phone: "11998765438",
      password: "senha123",
    },
    {
      name: "Otávio Campos",
      email: "otavio.campos@senaisp.org.br",
      phone: "11998765439",
      password: "senha123",
    },
    {
      name: "Rebeca Duarte",
      email: "rebeca.duarte@senaisp.org.br",
      phone: "11998765440",
      password: "senha123",
    },
    {
      name: "Rodrigo Freitas",
      email: "rodrigo.freitas@senaisp.org.br",
      phone: "11998765441",
      password: "senha123",
    },
    {
      name: "Sarah Gonçalves",
      email: "sarah.goncalves@senaisp.org.br",
      phone: "11998765442",
      password: "senha123",
    },
    {
      name: "Theo Macedo",
      email: "theo.macedo@senaisp.org.br",
      phone: "11998765443",
      password: "senha123",
    },
    {
      name: "Vitória Brandão",
      email: "vitoria.brandao@senaisp.org.br",
      phone: "11998765444",
      password: "senha123",
    },
    {
      name: "André Moraes",
      email: "andre.moraes@senaisp.org.br",
      phone: "11998765445",
      password: "senha123",
    },
    {
      name: "Bárbara Neves",
      email: "barbara.neves@senaisp.org.br",
      phone: "11998765446",
      password: "senha123",
    },
    {
      name: "Cauã Rocha",
      email: "caua.rocha@senaisp.org.br",
      phone: "11998765447",
      password: "senha123",
    },
    {
      name: "Cecília Siqueira",
      email: "cecilia.siqueira@senaisp.org.br",
      phone: "11998765448",
      password: "senha123",
    },
    {
      name: "Daniel Lira",
      email: "daniel.lira@senaisp.org.br",
      phone: "11998765449",
      password: "senha123",
    },
    {
      name: "Elisa Peixoto",
      email: "elisa.peixoto@senaisp.org.br",
      phone: "11998765450",
      password: "senha123",
    },
    {
      name: "Enzo Rangel",
      email: "enzo.rangel@senaisp.org.br",
      phone: "11998765451",
      password: "senha123",
    },
    {
      name: "Gabriela Drummond",
      email: "gabriela.drummond@senaisp.org.br",
      phone: "11998765452",
      password: "senha123",
    },
    {
      name: "Gustavo Silveira",
      email: "gustavo.silveira@senaisp.org.br",
      phone: "11998765453",
      password: "senha123",
    },
    {
      name: "Heloísa Guerra",
      email: "heloisa.guerra@senaisp.org.br",
      phone: "11998765454",
      password: "senha123",
    },
    {
      name: "Isaac Matos",
      email: "isaac.matos@senaisp.org.br",
      phone: "11998765455",
      password: "senha123",
    },
    {
      name: "Joana Cavalcanti",
      email: "joana.cavalcanti@senaisp.org.br",
      phone: "11998765456",
      password: "senha123",
    },
    {
      name: "Kevin Moura",
      email: "kevin.moura@senaisp.org.br",
      phone: "11998765457",
      password: "senha123",
    },
    {
      name: "Lívia Navarro",
      email: "livia.navarro@senaisp.org.br",
      phone: "11998765458",
      password: "senha123",
    },
    {
      name: "Marcos Paiva",
      email: "marcos.paiva@senaisp.org.br",
      phone: "11998765459",
      password: "senha123",
    },
    {
      name: "Maria Eduarda Pimentel",
      email: "maria.pimentel@senaisp.org.br",
      phone: "11998765460",
      password: "senha123",
    },
    {
      name: "Matheus Santana",
      email: "matheus.santana@senaisp.org.br",
      phone: "11998765461",
      password: "senha123",
    },
    {
      name: "Melissa Fogaça",
      email: "melissa.fogaca@senaisp.org.br",
      phone: "11998765462",
      password: "senha123",
    },
    {
      name: "Noah Caldeira",
      email: "noah.caldeira@senaisp.org.br",
      phone: "11998765463",
      password: "senha123",
    },
    {
      name: "Pietra Tavares",
      email: "pietra.tavares@senaisp.org.br",
      phone: "11998765464",
      password: "senha123",
    },
    {
      name: "Rafael Dantas",
      email: "rafael.dantas@senaisp.org.br",
      phone: "11998765465",
      password: "senha123",
    },
    {
      name: "Stella Bentes",
      email: "stella.bentes@senaisp.org.br",
      phone: "11998765466",
      password: "senha123",
    },
    {
      name: "Victor Queiroz",
      email: "victor.queiroz@senaisp.org.br",
      phone: "11998765467",
      password: "senha123",
    },
    {
      name: "Alice Chaves",
      email: "alice.chaves@senaisp.org.br",
      phone: "11998765468",
      password: "senha123",
    },
    {
      name: "Bernardo Guedes",
      email: "bernardo.guedes@senaisp.org.br",
      phone: "11998765469",
      password: "senha123",
    },
    {
      name: "Clara Leal",
      email: "clara.leal@senaisp.org.br",
      phone: "11998765470",
      password: "senha123",
    },
    {
      name: "Diego Bastos",
      email: "diego.bastos@senaisp.org.br",
      phone: "11998765471",
      password: "senha123",
    },
    {
      name: "Emanuelly Fontes",
      email: "emanuelly.fontes@senaisp.org.br",
      phone: "11998765472",
      password: "senha123",
    },
    {
      name: "Francisco Arruda",
      email: "francisco.arruda@senaisp.org.br",
      phone: "11998765473",
      password: "senha123",
    },
    {
      name: "Isabelly Telles",
      email: "isabelly.telles@senaisp.org.br",
      phone: "11998765474",
      password: "senha123",
    },
    {
      name: "Joaquim Bezerra",
      email: "joaquim.bezerra@senaisp.org.br",
      phone: "11998765475",
      password: "senha123",
    },
    {
      name: "Lorena Pinho",
      email: "lorena.pinho@senaisp.org.br",
      phone: "11998765476",
      password: "senha123",
    },
    {
      name: "Lorenzo Prado",
      email: "lorenzo.prado@senaisp.org.br",
      phone: "11998765477",
      password: "senha123",
    },
    {
      name: "Maitê Franco",
      email: "maite.franco@senaisp.org.br",
      phone: "11998765478",
      password: "senha123",
    },
    {
      name: "Murilo Aguiar",
      email: "murilo.aguiar@senaisp.org.br",
      phone: "11998765479",
      password: "senha123",
    },
    {
      name: "Olívia Furtado",
      email: "olivia.furtado@senaisp.org.br",
      phone: "11998765480",
      password: "senha123",
    },
    {
      name: "Paulo Navarro",
      email: "paulo.navarro@senaisp.org.br",
      phone: "11998765481",
      password: "senha123",
    },
    {
      name: "Rayssa Esteves",
      email: "rayssa.esteves@senaisp.org.br",
      phone: "11998765482",
      password: "senha123",
    },
    {
      name: "Sérgio Lemos",
      email: "sergio.lemos@senaisp.org.br",
      phone: "11998765483",
      password: "senha123",
    },
    {
      name: "Teodoro Barreto",
      email: "teodoro.barreto@senaisp.org.br",
      phone: "11998765484",
      password: "senha123",
    },
    {
      name: "Valentine Assis",
      email: "valentine.assis@senaisp.org.br",
      phone: "11998765485",
      password: "senha123",
    },
    {
      name: "Vicente Avelar",
      email: "vicente.avelar@senaisp.org.br",
      phone: "11998765486",
      password: "senha123",
    },
    {
      name: "Yago Meireles",
      email: "yago.meireles@senaisp.org.br",
      phone: "11998765487",
      password: "senha123",
    },
    {
      name: "Zilda Varejão",
      email: "zilda.varejao@senaisp.org.br",
      phone: "11998765488",
      password: "senha123",
    },
    {
      name: "Breno Amaral",
      email: "breno.amaral@senaisp.org.br",
      phone: "11998765489",
      password: "senha123",
    },
    {
      name: "Catarina Beltrão",
      email: "catarina.beltrao@senaisp.org.br",
      phone: "11998765490",
      password: "senha123",
    },
    {
      name: "Danilo Cordeiro",
      email: "danilo.cordeiro@senaisp.org.br",
      phone: "11998765491",
      password: "senha123",
    },
    {
      name: "Eloá Dornelles",
      email: "eloa.dornelles@senaisp.org.br",
      phone: "11998765492",
      password: "senha123",
    },
    {
      name: "Erick Goulart",
      email: "erick.goulart@senaisp.org.br",
      phone: "11998765493",
      password: "senha123",
    },
    {
      name: "Hadassa Guimarães",
      email: "hadassa.guimaraes@senaisp.org.br",
      phone: "11998765494",
      password: "senha123",
    },
    {
      name: "Ian Novais",
      email: "ian.novais@senaisp.org.br",
      phone: "11998765495",
      password: "senha123",
    },
    {
      name: "Laís Padrão",
      email: "lais.padrao@senaisp.org.br",
      phone: "11998765496",
      password: "senha123",
    },
    {
      name: "Levi Sampaio",
      email: "levi.sampaio@senaisp.org.br",
      phone: "11998765497",
      password: "senha123",
    },
    {
      name: "Maya Valente",
      email: "maya.valente@senaisp.org.br",
      phone: "11998765498",
      password: "senha123",
    },
    {
      name: "Nícolas Xavier",
      email: "nicolas.xavier@senaisp.org.br",
      phone: "11998765499",
      password: "senha123",
    },
    {
      name: "Sabrina Zamboni",
      email: "sabrina.zamboni@senaisp.org.br",
      phone: "11998765500",
      password: "senha123",
    },
  ];

  await prisma.user.createMany({ data: usersData });

  // === ITENS REAIS (100) ===
  const itemsData = [
    {
      title: "Garrafinha térmica Lululemon",
      description:
        "Garrafinha térmica rosa claro, 1 litro. Encontrada na cantina no dia 15/09 (manhã).",
      location: "Cantina",
      imageUrl: "https://i.ibb.co/LDKNpdNQ/d27f095a85763437fe96bc30095917b2.jpg",
      status: Status.ENCONTRADO,
      ownerId: 1,
      foundById: 2,
    },
    {
      title: "Mochila preta Nike",
      description: "Mochila preta com zíper vermelho e etiqueta escolar.",
      location: "Biblioteca",
      imageUrl: "https://i.ibb.co/6c9YCr15/mochila-nike-sb-heritage-preto-6603011e2dad0.jpg",
      status: Status.PERDIDO,
      ownerId: 3,
    },
    {
      title: "Carteira marrom de couro",
      description:
        "Carteira de couro marrom com cartões e documentos pessoais.",
      location: "Pátio",
      imageUrl: "https://i.ibb.co/pv7H7Lw4/produto-Arquivo-1157-1621-orig.jpg",
      status: Status.ENCONTRADO,
      ownerId: 4,
      foundById: 5,
    },
    {
      title: "Fone de ouvido JBL preto",
      description: "Fone JBL sem fio esquecido no laboratório de informática.",
      location: "Lab. de Informática",
      imageUrl: "https://i.ibb.co/LXh8G6jR/2685687210c5911ea66.webp.jpg",
      status: Status.PERDIDO,
      ownerId: 6,
    },
    {
      title: "Caderno azul com espiral",
      description: "Caderno azul com etiqueta do SENAI na capa.",
      location: "Sala 104",
      imageUrl: "https://i.ibb.co/HTdYB47t/images.jpg",
      status: Status.ENCONTRADO,
      ownerId: 7,
      foundById: 8,
    },
    {
      title: "Chave com chaveiro vermelho",
      description: "Chave pequena com chaveiro em formato de bola.",
      location: "Corredor principal",
      imageUrl: "https://i.ibb.co/j9GVs8SF/images.jpg",
      status: Status.ENCONTRADO,
      ownerId: 9,
      foundById: 10,
    },
    {
      title: "Casaco cinza Adidas",
      description: "Casaco de moletom cinza, tamanho M.",
      location: "Cantina",
      imageUrl: "https://i.ibb.co/G46B03K9/41y-Gqr-Ym-Bu-L-AC.jpg",
      status: Status.PERDIDO,
      ownerId: 11,
    },
    {
      title: "Pen drive Sandisk 32GB",
      description: "Pen drive preto Sandisk, encontrado na sala de aula.",
      location: "Sala 201",
      imageUrl: "https://i.ibb.co/SDdsN0RY/images.jpg",
      status: Status.ENCONTRADO,
      ownerId: 12,
      foundById: 13,
    },
    {
      title: "Óculos de grau preto",
      description: "Óculos de grau com armação escura, deixado no banheiro.",
      location: "Banheiro feminino",
      imageUrl: "https://i.ibb.co/mCNsqpBN/img-6500.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 14,
      foundById: 15,
    },
    {
      title: "Relógio digital Casio",
      description: "Relógio preto Casio esquecido no vestiário.",
      location: "Vestiário masculino",
      imageUrl: "https://i.ibb.co/twNwwTQZ/61kb-ZHf-PNz-L.jpg",
      status: Status.ENCONTRADO,
      ownerId: 16,
      foundById: 17,
    },
    // Início dos 90 itens gerados (itens 11-100)
    {
      title: "Carregador de celular Samsung",
      description: "Carregador branco, tipo C. Perdido perto do auditório.",
      location: "Auditório",
      imageUrl: "https://i.ibb.co/dJ5r7TDn/d1e47732a7f79dec3840618ca3055c34.webp.jpg",
      status: Status.PERDIDO,
      ownerId: 18,
    },
    {
      title: "Livro 'Cálculo I'",
      description: "Livro de capa azul, encontrado na biblioteca.",
      location: "Biblioteca",
      imageUrl: "https://i.ibb.co/3mdm5fyv/D-NQ-NP-775756-MLB79298913785-092024-O.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 19,
      foundById: 18,
    },
    {
      title: "Guarda-chuva preto",
      description:
        "Guarda-chuva grande, cabo de madeira. Esquecido na entrada.",
      location: "Entrada principal",
      imageUrl: "https://i.ibb.co/Rk49HvjM/guarda-chuva-preto-cabo-madeira-2195-1-3a8c5f3fcf434d8bdc54aad5dc0293f6.webp.jpg",
      status: Status.PERDIDO,
      ownerId: 20,
    },
    {
      title: "Calculadora científica HP",
      description: "Calculadora científica cinza, encontrada na sala 202.",
      location: "Sala 202",
      imageUrl: "https://i.ibb.co/mrDcLp2W/11476-1-2.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 21,
      foundById: 19,
    },
    {
      title: "Estojo rosa Tilibra",
      description: "Estojo rosa com muitos adesivos.",
      location: "Pátio",
      imageUrl: "https://i.ibb.co/4nBZ9h31/estojo-simples-m-dio-happy-rosa-tilibra-jsmlcgshey.webp.jpg",
      status: Status.PERDIDO,
      ownerId: 22,
    },
    {
      title: "Boné vermelho Nike",
      description: "Boné de aba curva, logo branco. Encontrado no ginásio.",
      location: "Ginásio",
      imageUrl: "https://i.ibb.co/YBXGBQxm/2469579403c42b6ed46.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 23,
      foundById: 20,
    },
    {
      title: "Chaves do carro (VW)",
      description: "Chave canivete Volkswagen com chaveiro do Star Wars.",
      location: "Estacionamento",
      imageUrl: "https://i.ibb.co/35Dmr2Sb/tiguan-1.jpg",
      status: Status.PERDIDO,
      ownerId: 24,
    },
    {
      title: "Agenda 2024 preta",
      description: "Agenda de capa dura preta, encontrada na sala 101.",
      location: "Sala 101",
      imageUrl: "https://i.ibb.co/rfc2LS3n/agenda-executiva-2024-dac-4106-maior-preta-35280723-1-4cda819a92ebf4df304c2c27d262cb61.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 25,
      foundById: 21,
    },
    {
      title: "Brinco de argola dourado",
      description: "Um brinco de argola (par perdido).",
      location: "Banheiro feminino",
      imageUrl: "https://i.ibb.co/RT9DkWTC/image.webp.jpg",
      status: Status.PERDIDO,
      ownerId: 26,
    },
    {
      title: "Pulseira de prata",
      description: "Pulseira fina com um pequeno pingente de coração.",
      location: "Refeitório",
      imageUrl: "https://i.ibb.co/jpkYRnh/pulseira-prata-925-3x1-u4b3bsbflb.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 27,
      foundById: 22,
    },
    {
      title: "Anel de formatura",
      description: "Anel com pedra azul, inscrição interna 'A.L. 2023'.",
      location: "Vestiário masculino",
      imageUrl: "https://i.ibb.co/QqZjQMs/ballet-mod01-ag-principal.webp.jpg",
      status: Status.PERDIDO,
      ownerId: 28,
    },
    {
      title: "Óculos de sol Ray-Ban",
      description: "Modelo Aviador, armação dourada, lente verde.",
      location: "Quadra",
      imageUrl: "https://i.ibb.co/5WQwV99x/Produto.webp.jpg",
      status: Status.ENCONTRADO,
      ownerId: 29,
      foundById: 23,
    },
    {
      title: "Pasta de couro sintético",
      description: "Pasta preta com zíper, perdida na secretaria.",
      location: "Secretaria",
      imageUrl: "https://example.com/pasta-couro.jpg",
      status: Status.PERDIDO,
      ownerId: 30,
    },
    {
      title: "Uniforme (Jaleco)",
      description: "Jaleco branco com logo do SENAI, bolso manchado de caneta.",
      location: "Lab. de Química",
      imageUrl: "https://example.com/jaleco.jpg",
      status: Status.ENCONTRADO,
      ownerId: 31,
      foundById: 24,
    },
    {
      title: "Squeeze azul",
      description: "Garrafa de água azul, 500ml, com adesivo 'Hydrate'.",
      location: "Ginásio",
      imageUrl: "https://example.com/squeeze-azul.jpg",
      status: Status.PERDIDO,
      ownerId: 32,
    },
    {
      title: "Caixa de som Bluetooth JBL (Go)",
      description: "Caixinha de som preta, modelo JBL Go. Encontrada no pátio.",
      location: "Pátio",
      imageUrl: "https://example.com/jbl-go.jpg",
      status: Status.ENCONTRADO,
      ownerId: 33,
      foundById: 25,
    },
    {
      title: "Tablet Samsung",
      description: "Tablet com capa rosa, tela trincada no canto.",
      location: "Biblioteca",
      imageUrl: "https://example.com/tablet-samsung.jpg",
      status: Status.PERDIDO,
      ownerId: 34,
    },
    {
      title: "Notebook Dell (carregador)",
      description:
        "Carregador de notebook Dell (ponta fina), encontrado na sala 301.",
      location: "Sala 301",
      imageUrl: "https://example.com/carregador-dell.jpg",
      status: Status.ENCONTRADO,
      ownerId: 35,
      foundById: 26,
    },
    {
      title: "Mouse sem fio Logitech",
      description:
        "Mouse preto, pequeno, perdido no laboratório de informática.",
      location: "Lab. de Informática",
      imageUrl: "https://example.com/mouse-logitech.jpg",
      status: Status.PERDIDO,
      ownerId: 36,
    },
    {
      title: "Teclado mecânico",
      description: "Teclado com luzes RGB, encontrado na sala 201.",
      location: "Sala 201",
      imageUrl: "https://example.com/teclado-mecanico.jpg",
      status: Status.ENCONTRADO,
      ownerId: 37,
      foundById: 27,
    },
    {
      title: "Jaqueta jeans",
      description: "Jaqueta jeans clara, tamanho P, com botons.",
      location: "Cantina",
      imageUrl: "https://example.com/jaqueta-jeans.jpg",
      status: Status.PERDIDO,
      ownerId: 38,
    },
    {
      title: "Livro 'O Pequeno Príncipe'",
      description: "Edição de capa dura, encontrado no corredor B.",
      location: "Corredor B",
      imageUrl: "https://example.com/pequeno-principe.jpg",
      status: Status.ENCONTRADO,
      ownerId: 39,
      foundById: 28,
    },
    {
      title: "Chave de casa (simples)",
      description: "Chave prateada única, sem chaveiro.",
      location: "Pátio",
      imageUrl: "https://example.com/chave-simples.jpg",
      status: Status.PERDIDO,
      ownerId: 40,
    },
    {
      title: "Fone de ouvido Apple (com fio)",
      description: "Fone original da Apple, com conector lightning.",
      location: "Biblioteca",
      imageUrl: "https://example.com/fone-apple.jpg",
      status: Status.ENCONTRADO,
      ownerId: 41,
      foundById: 29,
    },
    {
      title: "Carregador de iPhone",
      description: "Cabo e fonte, originais. Perdido na sala 104.",
      location: "Sala 104",
      imageUrl: "https://example.com/carregador-iphone.jpg",
      status: Status.PERDIDO,
      ownerId: 42,
    },
    {
      title: "Bolsa pequena preta",
      description: "Bolsa transversal com alça dourada.",
      location: "Banheiro feminino",
      imageUrl: "https://example.com/bolsa-preta.jpg",
      status: Status.ENCONTRADO,
      ownerId: 43,
      foundById: 30,
    },
    {
      title: "Tênis Adidas (um pé)",
      description: "Pé esquerdo de um tênis Adidas Superstar, branco.",
      location: "Vestiário masculino",
      imageUrl: "https://example.com/tenis-adidas.jpg",
      status: Status.PERDIDO,
      ownerId: 44,
    },
    {
      title: "Caderno de desenho",
      description: "Caderno grande, capa preta, com vários esboços.",
      location: "Sala 202",
      imageUrl: "https://example.com/caderno-desenho.jpg",
      status: Status.ENCONTRADO,
      ownerId: 45,
      foundById: 31,
    },
    {
      title: "Blusa de frio (Azul Marinho)",
      description: "Blusa de lã, gola V, tamanho M.",
      location: "Auditório",
      imageUrl: "https://example.com/blusa-la.jpg",
      status: Status.PERDIDO,
      ownerId: 46,
    },
    {
      title: "Hollister (Moletom)",
      description: "Moletom cinza com zíper, escrito Hollister em azul.",
      location: "Ginásio",
      imageUrl: "https://example.com/moletom-hollister.jpg",
      status: Status.ENCONTRADO,
      ownerId: 47,
      foundById: 32,
    },
    {
      title: "Airpods (Case)",
      description: "Caixinha de carregamento Airpods (vazia).",
      location: "Cantina",
      imageUrl: "https://example.com/case-airpods.jpg",
      status: Status.PERDIDO,
      ownerId: 48,
    },
    {
      title: "Documento (RG)",
      description: "Carteira de Identidade em nome de 'Carlos E. S.'.",
      location: "Secretaria",
      imageUrl: "https://example.com/documento-rg.jpg",
      status: Status.ENCONTRADO,
      ownerId: 49,
      foundById: 33,
    },
    {
      title: "Chaveiro (abridor)",
      description: "Chaveiro de metal em formato de abridor de garrafa.",
      location: "Refeitório",
      imageUrl: "https://example.com/chaveiro-abridor.jpg",
      status: Status.PERDIDO,
      ownerId: 50,
    },
    {
      title: "Bicicleta (Cadeado)",
      description:
        "Cadeado de bicicleta U-lock, preto. Encontrado no bicicletário.",
      location: "Bicicletário",
      imageUrl: "https://example.com/cadeado-u-lock.jpg",
      status: Status.ENCONTRADO,
      ownerId: 51,
      foundById: 34,
    },
    {
      title: "Kindle",
      description: "Kindle Paperwhite com capa azul.",
      location: "Biblioteca",
      imageUrl: "https://example.com/kindle.jpg",
      status: Status.PERDIDO,
      ownerId: 52,
    },
    {
      title: "Controle de portão",
      description: "Controle preto, marca PPA. Encontrado no estacionamento.",
      location: "Estacionamento",
      imageUrl: "https://example.com/controle-portao.jpg",
      status: Status.ENCONTRADO,
      ownerId: 53,
      foundById: 35,
    },
    {
      title: "Powerbank",
      description: "Carregador portátil preto, marca Xiaomi.",
      location: "Sala 101",
      imageUrl: "https://example.com/powerbank-xiaomi.jpg",
      status: Status.PERDIDO,
      ownerId: 54,
    },
    {
      title: "Presilha de cabelo",
      description: "Presilha grande (piranha), cor tartaruga.",
      location: "Banheiro feminino",
      imageUrl: "https://example.com/presilha.jpg",
      status: Status.ENCONTRADO,
      ownerId: 55,
      foundById: 36,
    },
    {
      title: "Cartão de transporte (Bilhete Único)",
      description: "Cartão de estudante, nome 'Mariana G.'.",
      location: "Pátio",
      imageUrl: "https://example.com/bilhete-unico.jpg",
      status: Status.PERDIDO,
      ownerId: 56,
    },
    {
      title: "Marmita (Tupperware)",
      description: "Pote de vidro com tampa verde, encontrado no refeitório.",
      location: "Refeitório",
      imageUrl: "https://example.com/marmita.jpg",
      status: Status.ENCONTRADO,
      ownerId: 57,
      foundById: 37,
    },
    {
      title: "Protetor labial",
      description: "Nivea azul, perdido na cantina.",
      location: "Cantina",
      imageUrl: "https://example.com/protetor-labial.jpg",
      status: Status.PERDIDO,
      ownerId: 58,
    },
    {
      title: "HD Externo",
      description: "HD Externo Seagate 1TB, cabo azul.",
      location: "Lab. de Informática",
      imageUrl: "https://example.com/hd-externo.jpg",
      status: Status.ENCONTRADO,
      ownerId: 59,
      foundById: 38,
    },
    {
      title: "Par de luvas (preto)",
      description: "Luvas de lã pretas, tamanho único.",
      location: "Corredor principal",
      imageUrl: "https://example.com/luvas-pretas.jpg",
      status: Status.PERDIDO,
      ownerId: 60,
    },
    {
      title: "Moeda (antiga)",
      description: "Moeda de 1 real das Olimpíadas (Boxe).",
      location: "Pátio",
      imageUrl: "https://example.com/moeda-olimpiadas.jpg",
      status: Status.ENCONTRADO,
      ownerId: 61,
      foundById: 39,
    },
    {
      title: "Violão (Capa)",
      description: "Capa de violão preta, vazia. Esquecida no auditório.",
      location: "Auditório",
      imageUrl: "https://example.com/capa-violao.jpg",
      status: Status.PERDIDO,
      ownerId: 62,
    },
    {
      title: "Escova de cabelo",
      description: "Escova tipo raquete, cor rosa.",
      location: "Vestiário feminino",
      imageUrl: "https://example.com/escova-cabelo.jpg",
      status: Status.ENCONTRADO,
      ownerId: 63,
      foundById: 40,
    },
    {
      title: "Crachá (sem identificação)",
      description: "Crachá de visitante, número 042.",
      location: "Entrada principal",
      imageUrl: "https://example.com/cracha-visitante.jpg",
      status: Status.PERDIDO,
      ownerId: 64,
    },
    {
      title: "Livro da Biblioteca",
      description: "Livro '1984', com etiqueta da biblioteca.",
      location: "Sala 102",
      imageUrl: "https://example.com/livro-1984.jpg",
      status: Status.ENCONTRADO,
      ownerId: 65,
      foundById: 41,
    },
    {
      title: "Copo Stanley (Verde)",
      description: "Copo térmico verde, com tampa. Perdido na quadra.",
      location: "Quadra",
      imageUrl: "https://example.com/copo-stanley.jpg",
      status: Status.PERDIDO,
      ownerId: 66,
    },
    {
      title: "Bola de vôlei",
      description: "Bola Mikasa, encontrada no ginásio após o horário.",
      location: "Ginásio",
      imageUrl: "https://example.com/bola-volei.jpg",
      status: Status.ENCONTRADO,
      ownerId: 67,
      foundById: 42,
    },
    {
      title: "Adaptador de tomada",
      description: "Adaptador universal, branco.",
      location: "Sala 301",
      imageUrl: "https://example.com/adaptador-tomada.jpg",
      status: Status.PERDIDO,
      ownerId: 68,
    },
    {
      title: "Maço de cigarros (fechado)",
      description: "Maço de Marlboro vermelho, encontrado no estacionamento.",
      location: "Estacionamento",
      imageUrl: "https://example.com/maco-cigarro.jpg",
      status: Status.ENCONTRADO,
      ownerId: 69,
      foundById: 43,
    },
    {
      title: "Óculos de sol (Oakley)",
      description: "Modelo esportivo, armação preta, lente espelhada.",
      location: "Quadra",
      imageUrl: "https://example.com/oculos-oakley.jpg",
      status: Status.PERDIDO,
      ownerId: 70,
    },
    {
      title: "Camiseta de time (Corinthians)",
      description: "Camiseta preta, número 10. Encontrada no vestiário.",
      location: "Vestiário masculino",
      imageUrl: "https://example.com/camiseta-corinthians.jpg",
      status: Status.ENCONTRADO,
      ownerId: 71,
      foundById: 44,
    },
    {
      title: "Fones de ouvido (com fio, genérico)",
      description: "Fones pretos, simples, marca 'Inova'.",
      location: "Biblioteca",
      imageUrl: "https://example.com/fone-generico.jpg",
      status: Status.PERDIDO,
      ownerId: 72,
    },
    {
      title: "Relógio de pulso (Analógico)",
      description: "Relógio dourado, marca 'Orient', pulseira de metal.",
      location: "Banheiro masculino",
      imageUrl: "https://example.com/relogio-orient.jpg",
      status: Status.ENCONTRADO,
      ownerId: 73,
      foundById: 45,
    },
    {
      title: "Garrafa de café (térmica)",
      description: "Garrafa de inox, 500ml, com café dentro.",
      location: "Sala dos Professores",
      imageUrl: "https://example.com/garrafa-cafe.jpg",
      status: Status.PERDIDO,
      ownerId: 74,
    },
    {
      title: "Chaveiro (Pelúcia)",
      description: "Chaveiro do Pikachu, encontrado no corredor B.",
      location: "Corredor B",
      imageUrl: "https://example.com/chaveiro-pikachu.jpg",
      status: Status.ENCONTRADO,
      ownerId: 75,
      foundById: 46,
    },
    {
      title: "Isqueiro (Bic)",
      description: "Isqueiro azul, perdido perto da entrada.",
      location: "Entrada principal",
      imageUrl: "https://example.com/isqueiro-bic.jpg",
      status: Status.PERDIDO,
      ownerId: 76,
    },
    {
      title: "Câmera (Instax Mini)",
      description: "Câmera instantânea rosa, encontrada na cantina.",
      location: "Cantina",
      imageUrl: "https://example.com/instax-mini.jpg",
      status: Status.ENCONTRADO,
      ownerId: 77,
      foundById: 47,
    },
    {
      title: "Livro 'O Hobbit'",
      description: "Edição de bolso, capa verde.",
      location: "Pátio",
      imageUrl: "https://example.com/livro-hobbit.jpg",
      status: Status.PERDIDO,
      ownerId: 78,
    },
    {
      title: "Notebook (Capa)",
      description: "Capa de notebook preta, 15 polegadas, zíper quebrado.",
      location: "Sala 201",
      imageUrl: "https://example.com/capa-notebook.jpg",
      status: Status.ENCONTRADO,
      ownerId: 79,
      foundById: 48,
    },
    {
      title: "Chapéu (Preto)",
      description: "Chapéu de feltro preto, estilo 'Fedora'.",
      location: "Auditório",
      imageUrl: "https://example.com/chapeu-fedora.jpg",
      status: Status.PERDIDO,
      ownerId: 80,
    },
    {
      title: "Controle de Ar Condicionado",
      description: "Controle universal, encontrado na sala 102.",
      location: "Sala 102",
      imageUrl: "https://example.com/controle-ar.jpg",
      status: Status.ENCONTRADO,
      ownerId: 81,
      foundById: 49,
    },
    {
      title: "Tubo de cola (Bastão)",
      description: "Cola Pritt, grande. Perdida na biblioteca.",
      location: "Biblioteca",
      imageUrl: "https://example.com/cola-pritt.jpg",
      status: Status.PERDIDO,
      ownerId: 82,
    },
    {
      title: "Apontador (com depósito)",
      description: "Apontador Faber-Castell, azul. Encontrado na sala 104.",
      location: "Sala 104",
      imageUrl: "https://example.com/apontador.jpg",
      status: Status.ENCONTRADO,
      ownerId: 83,
      foundById: 50,
    },
    {
      title: "Desodorante",
      description:
        "Desodorante aerosol Rexona, masculino. Esquecido no vestiário.",
      location: "Vestiário masculino",
      imageUrl: "https://example.com/desodorante.jpg",
      status: Status.PERDIDO,
      ownerId: 84,
    },
    {
      title: "Carimbo (Professor)",
      description: "Carimbo com o nome 'Prof. Helena M.'.",
      location: "Sala dos Professores",
      imageUrl: "https://example.com/carimbo.jpg",
      status: Status.ENCONTRADO,
      ownerId: 85,
      foundById: 51,
    },
    {
      title: "Camisa Social (Branca)",
      description: "Camisa branca, tamanho G, dobrada. Perdida no auditório.",
      location: "Auditório",
      imageUrl: "https://example.com/camisa-social.jpg",
      status: Status.PERDIDO,
      ownerId: 86,
    },
    {
      title: "Garrafa de iogurte",
      description: "Garrafa de 'Yakult', encontrada vazia na sala 202.",
      location: "Sala 202",
      imageUrl: "https://example.com/yakult.jpg",
      status: Status.ENCONTRADO,
      ownerId: 87,
      foundById: 52,
    },
    {
      title: "Sapato social (preto)",
      description: "Sapato social masculino, pé direito, marca 'Democrata'.",
      location: "Estacionamento",
      imageUrl: "https://example.com/sapato-social.jpg",
      status: Status.PERDIDO,
      ownerId: 88,
    },
    {
      title: "Grampeador",
      description: "Grampeador pequeno, preto. Encontrado na secretaria.",
      location: "Secretaria",
      imageUrl: "https://example.com/grampeador.jpg",
      status: Status.ENCONTRADO,
      ownerId: 89,
      foundById: 53,
    },
    {
      title: "Pacote de bolachas (fechado)",
      description: "Pacote de 'Passatempo', recheio de chocolate.",
      location: "Cantina",
      imageUrl: "https://example.com/bolacha.jpg",
      status: Status.PERDIDO,
      ownerId: 90,
    },
    {
      title: "Batom (vermelho)",
      description: "Batom da marca MAC, cor Ruby Woo. Encontrado no banheiro.",
      location: "Banheiro feminino",
      imageUrl: "https://example.com/batom-mac.jpg",
      status: Status.ENCONTRADO,
      ownerId: 91,
      foundById: 54,
    },
    {
      title: "Mousepad",
      description: "Mousepad preto, simples. Perdido no Lab. de Informática.",
      location: "Lab. de Informática",
      imageUrl: "https://example.com/mousepad.jpg",
      status: Status.PERDIDO,
      ownerId: 92,
    },
    {
      title: "Caneta (Marca-texto)",
      description: "Marca-texto amarelo, Faber-Castell.",
      location: "Biblioteca",
      imageUrl: "https://example.com/marca-texto.jpg",
      status: Status.ENCONTRADO,
      ownerId: 93,
      foundById: 55,
    },
    {
      title: "Touca de natação",
      description: "Touca de silicone preta, marca 'Speedo'.",
      location: "Vestiário masculino",
      imageUrl: "https://example.com/touca-natacao.jpg",
      status: Status.PERDIDO,
      ownerId: 94,
    },
    // --- Itens adicionados para completar 100 ---
    {
      title: "Álcool em gel",
      description: "Frasco pequeno, com chaveiro, 'Giovanna Baby'.",
      location: "Pátio",
      imageUrl: "https://example.com/alcool-gel.jpg",
      status: Status.ENCONTRADO,
      ownerId: 95,
      foundById: 56,
    },
    {
      title: "Óculos de natação",
      description: "Óculos Speedo, lente azul.",
      location: "Vestiário masculino",
      imageUrl: "https://example.com/oculos-natacao.jpg",
      status: Status.PERDIDO,
      ownerId: 96,
    },
    {
      title: "Dinheiro (R$ 50,00)",
      description: "Uma nota de R$ 50,00 encontrada no corredor.",
      location: "Corredor principal",
      imageUrl: "https://example.com/dinheiro-50.jpg",
      status: Status.ENCONTRADO,
      ownerId: 97,
      foundById: 57,
    },
    {
      title: "Caderneta (tipo Moleskine)",
      description: "Caderneta preta, pequena, com elástico.",
      location: "Refeitório",
      imageUrl: "https://example.com/moleskine.jpg",
      status: Status.PERDIDO,
      ownerId: 98,
    },
    {
      title: "Band-aid (caixa)",
      description: "Caixa de Band-aid, quase cheia. Encontrada no ginásio.",
      location: "Ginásio",
      imageUrl: "https://example.com/band-aid.jpg",
      status: Status.ENCONTRADO,
      ownerId: 99,
      foundById: 58,
    },
    {
      title: "Anel (Bijuteria)",
      description: "Anel de metal prateado com pedra falsa (verde).",
      location: "Banheiro feminino",
      imageUrl: "https://example.com/anel-bijuteria.jpg",
      status: Status.PERDIDO,
      ownerId: 100,
    },
  ];

  await prisma.item.createMany({ data: itemsData });

  console.log(
    "✅ Seed criado com sucesso com 100 usuários (senha123) e 100 itens fixos!"
  );
}

main()
  .then(async () => await prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
